services:
  redis:
    image: redis:7-alpine
    container_name: fastapi-redis-demo-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    container_name: fastapi-redis-demo-web
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    container_name: fastapi-redis-demo-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    command: python worker.py

networks:
  app-network:
    driver: bridge